[project]
name = "audio-batch"
description = "Audio batch creation, extraction, information, resample, mono and stereo conversion."
version = "1.1.0"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/set-soft/ComfyUI-AudioBatch"

[tool.comfy]
PublisherId = "set-soft"
DisplayName = "Audio Batch"
